name: Create Tag Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0
    - name: Git Version
      uses: codacy/git-version@2.2.0
      id: create_version
    - name : Log
      id: version
      run: echo "::set-output name=version::$(steps.create_version.outputs.version)\n"
    - name: Create Tag
      uses: Klemensas/action-autotag@stable
      with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          version: "${{ steps.version.outputs.version }}"
