name: Create Tag Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Git Version
      uses: codacy/git-version@2.2.0
    - name: Create Tag
      uses: Klemensas/action-autotag@stable
      with:
          tag_prefix: "v"
          tag_suffix: "-dev"
