name: Main Version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0
    - name: Git Version
      uses: codacy/git-version@2.2.0
      id: create_version
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
    - name: Set Version
      run: 
        git config --global user.email "ggamegg170@gmail.com";
        git config --global user.name "R.Phuwanat";
        npm version ${{ steps.create_version.outputs.version }};
        git push | echo "${{ secrets.GITHUB_TOKEN }}" | echo "";
    - name: Create Tag
      uses: Klemensas/action-autotag@stable
      with:
          #version: ${{ steps.create_version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
